export const GET_BASICINFO = 'GET_BASICINFO';
export const DELETE_BASICINFO = 'DELETE_BASICINFO';
export const ADD_BASICINFO = 'ADD_BASICINFO';
export const GET_ERRORS = 'GET_ERRORS';
export const CREATE_MESSAGE = 'GET_MESSAGE';
