# Generated by Django 2.2.7 on 2019-11-18 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listingTitle', models.TextField()),
                ('listing', models.TextField()),
                ('listingKeywords', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listingInfo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedResume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('education1', models.TextField(blank=True)),
                ('education2', models.TextField(blank=True, null=True)),
                ('workHistory', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('relevantExperience1', models.TextField(blank=True, null=True)),
                ('relevantExperience2', models.TextField(blank=True, null=True)),
                ('relevantExperience3', models.TextField(null=True)),
                ('listingID', models.IntegerField(blank=True, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generatedResume', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
