# Generated by Django 2.2.7 on 2019-11-21 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedresume',
            name='workHistory',
        ),
        migrations.AddField(
            model_name='generatedresume',
            name='relevant_job_history1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedresume',
            name='relevant_job_history2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedresume',
            name='relevant_job_history3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
