# Generated by Django 2.2.6 on 2019-11-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedresume',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
