# Generated by Django 3.0 on 2019-12-16 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_auto_20191121_0405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedresume',
            name='education2',
        ),
    ]
