# Generated by Django 2.2.6 on 2019-11-06 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedresume',
            name='listingID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generatedresume',
            name='relevantExperience1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generatedresume',
            name='relevantExperience2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
