# Generated by Django 2.2.6 on 2019-11-05 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedResume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('education', models.TextField()),
                ('workHistory', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('relevantExperience1', models.TextField()),
                ('relevantExperience2', models.TextField()),
                ('relevantExperience3', models.TextField(null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generatedResume', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
