# Generated by Django 2.2.6 on 2019-11-06 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_generatedresume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedresume',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='generatedresume',
            name='email',
            field=models.EmailField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='generatedresume',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='generatedresume',
            name='workHistory',
            field=models.TextField(blank=True),
        ),
    ]
