// auth
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'USER_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

// resume
export const FETCH_EXPERIENCES = 'FETCH_EXPERIENCES';
export const REMOVE_EXPERIENCE = 'REMOVE_EXPERIENCE';
export const ADD_EXPERIENCE = 'ADD_EXPERIENCE';
export const EDIT_EXPERIENCE = 'EDIT_EXPERIENCE';
export const FETCH_EDUCATIONS = 'FETCH_EDUCATIONS';
export const DELETE_EDUCATION = 'DELETE_EDUCATION';
export const ADD_EDUCATION = 'ADD_EDUCATION';
export const FETCH_BASIC_INFO = 'FETCH_BASIC_INFO';
export const UPDATE_BASIC_INFO = 'UPDATE_BASIC_INFO';
