// auth
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'USER_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

// resume
export const FETCH_EXPERIENCES = 'FETCH_EXPERIENCES';
export const REMOVE_EXPERIENCE = 'REMOVE_EXPERIENCE';
export const ADD_EXPERIENCE = 'ADD_EXPERIENCE';
export const EDIT_EXPERIENCE = 'EDIT_EXPERIENCE';
export const FETCH_EDUCATIONS = 'FETCH_EDUCATIONS';
export const ADD_EDUCATION = 'ADD_EDUCATION';
export const EDIT_EDUCATION = 'EDIT_EDUCATION';
export const DELETE_EDUCATION = 'DELETE_EDUCATION';
export const FETCH_BASIC_INFO = 'FETCH_BASIC_INFO';
export const UPDATE_BASIC_INFO = 'ADD_BASIC_INFO';
export const FETCH_GENERATED = 'FETCH_GENERATED';
export const FETCH_LISTINGS = 'FETCH_LISTINGS';
export const EDIT_LISTING = 'EDIT_LISTING';
export const DELETE_LISTING = "DELETE_LISTING";
export const ADD_LISTING = "ADD_LISTING";
export const ADD_RESUME = "ADD_RESUME";
export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGES";
export const ADD_JOB_HISTORY = "ADD_JOB_HISTORY";
export const EDIT_JOB_HISTORY = "EDIT_JOB_HISTORY";
export const FETCH_JOB_HISTORY = "FETCH_JOB_HISTORY";
export const REMOVE_JOB_HISTORY = "REMOVE_JOB_HISTORY";

// date format
export const DATE_FORMAT = "YYYY-MM-DD";
