# Generated by Django 2.2.6 on 2019-10-27 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('education', models.TextField()),
                ('workHistory', models.TextField()),
                ('experience1', models.CharField(blank=True, max_length=400)),
                ('experience2', models.CharField(blank=True, max_length=400)),
                ('experience3', models.CharField(blank=True, max_length=400)),
                ('experience4', models.CharField(blank=True, max_length=400)),
                ('experience5', models.CharField(blank=True, max_length=400)),
                ('experience6', models.CharField(blank=True, max_length=400)),
                ('experience7', models.CharField(blank=True, max_length=400)),
                ('experience8', models.CharField(blank=True, max_length=400)),
                ('experience9', models.CharField(blank=True, max_length=400)),
                ('experience10', models.CharField(blank=True, max_length=400)),
                ('experience11', models.CharField(blank=True, max_length=400)),
                ('experience12', models.CharField(blank=True, max_length=400)),
                ('experience13', models.CharField(blank=True, max_length=400)),
                ('experience14', models.CharField(blank=True, max_length=400)),
                ('experience15', models.CharField(blank=True, max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
