# Generated by Django 2.2.6 on 2019-11-06 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicinfo',
            name='workHistory',
        ),
        migrations.AddField(
            model_name='experienceinfo',
            name='experienceType',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
