# Generated by Django 2.2.6 on 2019-11-04 01:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20191104_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experienceinfo',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experienceInfo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='experiencekeywords',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experienceKeywords', to=settings.AUTH_USER_MODEL),
        ),
    ]
