# Generated by Django 2.2.6 on 2019-10-30 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_experienceinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicinfo',
            name='workExperience',
        ),
    ]
