# Generated by Django 2.2.6 on 2019-11-06 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20191106_0203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experienceinfo',
            old_name='experience',
            new_name='experienceText',
        ),
    ]
