# Generated by Django 2.2.7 on 2019-11-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20191116_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
