# Generated by Django 2.2.6 on 2019-11-09 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_experience_experiencekeywords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='experienceKeywords',
            new_name='experience_keywords',
        ),
    ]
